name: "🚨 Hot Fix"
description: "급하게 수정해야할 이슈를 작성하세요!"
labels: "🚨 Hot Fix"
body:
  - type: textarea
    attributes:
      label: 🚨 설명
      description: 급하게 수정해야할 이슈에 대한 설명을 작성해 주세요.
      placeholder: 꼼꼼하게 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🌏 환경
      description: 이슈가 발생한 환경에 대해 작성해 주세요.
      placeholder: ◻︎ User Entity 작성
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 덧붙일 말
      description: 더 하고 싶은 말이 있다면 작성해 주세요.
